package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 26 13:42:48 AST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for BusinessUnitInfoView1.
     * @return BusinessUnitInfoView1
     */
    public ViewObjectImpl getBusinessUnitInfoView1() {
        return (ViewObjectImpl) findViewObject("BusinessUnitInfoView1");
    }
}

